---
# - name: Installing Homebrew Cask Packages (Git)
#   ansible.builtin.homebrew_cask:
#     state: present
#     name: adoptopenjdk

- name: Install Homebrew Packages (Git)
  ansible.builtin.homebrew:
    state: present
    name: 
    - git
    - bash-completion
    - pre-commit
    - gawk
    - coreutils
    #- git-credential-manager