---
- name: Installing apt Packages (Git)
  ansible.builtin.apt:
    state: present
    name:
      - git
      - bash-completion
      - coreutils
      - python-pkg-resources
      - python3-setuptools

    update_cache: yes
