---
- name: Installing apt Packages (Git)
  become: True
  ansible.builtin.apt:
    state: present
    name:
      - git
      - bash-completion
      - coreutils
      - shellcheck
    update_cache: yes
