---
- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: nix.yml
  when: ansible_os_family != 'Windows'

- include_tasks: Windows.yml
  when: ansible_os_family == 'Windows'

- include_tasks: git_config.yml

- name: Install pip packages
  pip:
    name: pre-commit
    executable: pip3
    extra_args: --user
