---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include: Windows.yml
  when: ansible_os_family == 'Windows'

- include: nix.yml
  when: ansible_os_family != 'Windows'

- include: git_config.yml
