---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include: nix.yml
  when: ansible_os_family != 'Windows'

- include: Windows.yml
  when: ansible_os_family == 'Windows'

- include: git_config.yml

- name: Install pip packages
  pip:
    name: pre-commit
    executable: pip3
    extra_args: --user
