---
- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: osx.yml
  when: ansible_os_family == 'Darwin'

- ansible.builtin.include_tasks: nix.yml
  when: ansible_os_family != 'Windows'

- ansible.builtin.include_tasks: Windows.yml
  when: ansible_os_family == 'Windows'

- ansible.builtin.include_tasks: git_config.yml

- name: Install pip packages
  ansible.builtin.pip:
    name:
      - pre-commit
      - lastversion
    executable: pip3
    extra_args: --user
