---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include: Windows.yml
  when: ansible_os_family == 'Windows'

- include: bash.yml
  when: ansible_os_family != 'Windows'

- include: git_config.yml

# - name: Create .gitconfig from template
#   ansible.builtin.template:
#     src: gitconfig.j2
#     dest: "{{ git_user_home_path | default(git_user_home_path_default, true) }}/.gitconfig"
#     owner: "{{ git_user_name }}"
#     mode: u=rw,g=r,o=r
