---
- name: Ensure .bash_profile exists
  ansible.builtin.file:
    path: "~{{ git_user_id }}/.bash_profile"
    state: touch
    owner: "{{ git_user_id }}"
    group: "{{ git_user_group_id }}"
    mode: "u=rw,g=r,o=r"
    modification_time: preserve
    access_time: preserve

- name: Add bash-completion to bash_profile
  ansible.builtin.lineinfile:
    path: "~{{ git_user_id }}/.bash_profile"
    line: 'source /usr/local/etc/profile.d/bash_completion.sh'
    owner: "{{ git_user_id }}"
    group: "{{ git_user_group_id }}"
    mode: "u=rw,g=r,o=r"

- name: Add show dirty state to bash_profile
  ansible.builtin.lineinfile:
    path: "~{{ git_user_id }}/.bash_profile"
    line: 'GIT_PS1_SHOWDIRTYSTATE=true'
    owner: "{{ git_user_id }}"
    group: "{{ git_user_group_id }}"
    mode: "u=rw,g=r,o=r"
