- name: Ensure .zshrc.local exists
  ansible.builtin.file:
    path: "{{ git_user_home_path | default(git_user_home_path_default, true) }}/.zshrc.local"
    state: touch
    mode: "u=rw,g=r,o=r"
    owner: "{{ git_user_id }}"

- name: Add Git completion for zsh
  ansible.builtin.lineinfile:
    path: "{{ git_user_home_path | default(git_user_home_path_default, true) }}/.zshrc.local"
    line: 'autoload -Uz compinit && compinit'

# setup zsh completion
# autoload -Uz compinit && compinit
