---
- name: Converge
  hosts: all
  tasks:
    - name: Include git
      include_role:
        name: ansible-role-git
      vars:
        git_user_email: user@email.com
        git_user_id: chris
        git_user_full_name: Chris Diehl
