---
- name: Dependency
  hosts: all
  tasks:
    - name: Add the user needed to test role with defaults
      ansible.builtin.user:
        name: chris

    - name: Install Python packages (Linux)
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - virtualenv
          - python-pkg-resources
          - python3-setuptools
        state: "present"
        update_cache: true
