name: Ansible CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Lint Ansible Role
      uses: ansible/ansible-lint-action@master
      with:
        targets:
          tests/test.yml

    - name: molecule
      uses: robertdebock/molecule-action@2.6.17