name: Ansible CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: "${{ github.repository }}"
    
    - name: Lint Ansible Role
      uses: ansible/ansible-lint-action@master
      with:
        targets:
          tests/test.yml

  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: "${{ github.repository }}"

    - name: molecule
      uses: robertdebock/molecule-action@2.6.17

  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'