name: Ansible CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Role
      uses: ansible/ansible-lint-action@master
      with:
        targets:
          tests/test.yml
    - name: Copy role
      run: |
        ls -la ./
        mkdir -p ${ROLES_DIR}/git
        cp -Rv ./* ${ROLES_DIR}/git
        echo "================="
        ls -la ${ROLES_DIR}
        echo "================="
        ls -la ${ROLES_DIR}git
      env:
        ROLES_DIR: /github/workspace/tests/roles
    - name: Install Ansible role
      uses: saubermacherag/ansible-playbook-docker-action@v1.4
      with:
        playbookName: tests/test.yml
        inventoryFile: tests/inventory
        rolesPath: .ansible/playbooks/roles
        verbosity: "vv"
      env:
        ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python