name: Ansible CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: "${{ github.repository }}"
    
    - name: Lint Ansible Role
      uses: ansible/ansible-lint-action@master
      with:
        targets:
          tests/test.yml

    - name: molecule
      uses: robertdebock/molecule-action@2.6.17